// <auto-generated />
namespace CodeFirstAproach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtablevehicleandperson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtablevehicleandperson));
        
        string IMigrationMetadata.Id
        {
            get { return "202105071707016_ add table vehicle and person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
